## dataset arguments
# field_separator: '/t'
# seq_separator: ' '
'USER_ID_FIELD': 'user_id'
'ITEM_ID_FIELD': 'item_id' # 'tag_id
# RATING_FIELD:
# TIME_FIELD:
# seq_len: 1

'load_col':
  'inter': [ 'item_id', 'timestamp', 'user_id' ]
  'item': ['item_id', 'total_order', 'total_sales']
  'user': ['user_id', 'user_total_orders', 'user_total_pur']